### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by zouyaoji** [d2-projects/d2-advance#5]
您好，项目很棒。我想咨询一下如果不是用vue-cli的初始化的项目这个插件该咋个用 - -
[@d2-projects/vue-filename-injector](https://github.com/d2-projects/vue-filename-injector)

**Comment by Aysnine** [comment]
vue-filename-injector 的初衷是针对 .vue 单文件组件自动注入代码，而 .vue 单文件是由 vue-loader 解析的，所以 vue-filename-injector 依赖于 vue-loader，如果你的项目是 webpack 并使用了 vue-loader，那就可以使用 vue-filename-injector，它本质上也是一个 loader，需要放在 vue-loader 之前。

非 vue- cli 的项目我目前也没试过，后期会尝试去做，如果对此还有什么疑惑可以回复这个 issue :)

**Comment by zouyaoji** [comment]
等你尝试非 vue- cli 的项目的时候我再学习一下，看看能不能借鉴一下-，我用的 rollup，我目前还是老实手写把文件关系敲出来了的 - -
